---
title: "Code"
output: github_document
---

# Temperature data, cell level

## ERA5-Land monthly averaged data

Source: https://doi.org/10.24381/cds.68d2bb30

For temperature data, I use the ERA5-Land dataset from Copernicus. It provides "2m temperature" at grid cell level, with a resolution of 0.1°, and a monthly frequency from 2000 to 2019.

Net-Migration and GDP data have a resolution of 0.083°. I downscale them to a coarser resolution of 0.1° to match them with climate data.

```{r}
library(ncdf4)
library(terra)

# 1) Load data

filename <- "../data/2m_temperature.nc"
nc <- nc_open(filename)

# Load latitude and longitude
lat <- ncvar_get(nc, "latitude") # 1801
lon <- ncvar_get(nc, "longitude") # 3600

lon <- ifelse(lon > 180, lon - 360, lon) # Center Europe
lon_order <- order(lon) 
lon <- lon[lon_order] # Reorder starting from the "new" 0

time <- ncvar_get(nc, "valid_time") # Read time: 12 months * 20 years = 240 months
dates <- as.POSIXct(time, origin = "1970-01-01", tz = "UTC") # Convert from seconds to date
years <- format(dates, "%Y")
years_unique <- unique(years) # 2000-2019

# Read temperature
temp_k <- ncvar_get(nc, "t2m")  # Three dimensions: [lon, lat, time]
temp_c <- temp_k[lon_order, , ] - 273.15  # Reoder and convert from Kelvin to Celsius

nc_close(nc)
rm(nc) # free memory
rm(temp_k) # free memory
gc() # free memory

# 2) Create rasters and compute year average

dir.create("temp_year_rasters", showWarnings = FALSE) # Create folder

# Loop years
for (j in seq_along(years_unique)) {
  yr <- years_unique[j]
  print(yr)
  idx <- which(years == yr) # Subset months with year

  month_rasters <- vector("list", length(idx))

  for (k in seq_along(idx)) {
    print(k)

    # Create a raster for each month
    r <- rast(t(temp_c[,,idx[k]]))
    ext(r) <- ext(min(lon), max(lon), min(lat), max(lat)) # Set Extent
    crs(r) <- "EPSG:4326" # Set CRS WGS84

    # Remove Antarctica: below -60°
    r <- crop(r, ext(min(lon), max(lon), -60, max(lat)))

    month_rasters[[k]] <- r
  }

  # Compute year mean
  yearly_raster <- mean(rast(month_rasters), na.rm = TRUE)
  
  # Global mean temperature for the year
  mean_value <- global(yearly_raster, fun = "mean", na.rm = TRUE)[1,1]
  cat("Year:", yr, "- Mean temp (°C):", round(mean_value, 2), "\n")
  
  # Name the raster layer with the year
  names(yearly_raster) <- paste0("temp_", yr)
  
  writeRaster(yearly_raster, sprintf("temp_year_rasters/year_%s.tif", yr), overwrite = TRUE)

  rm(month_rasters) # free memory
  gc() # free memory
}

rm(temp_c)
rm(r)
rm(temp_c_slice)
rm(yearly_raster)
gc()

# 3) Yearly rasters

yearly_files <- list.files("temp_year_rasters", pattern = "\\.tif$", full.names = TRUE)

# Read all rasters into a stack
yearly_rasters <- rast(yearly_files)

r_2000 <- yearly_rasters[[1]]  # First raster (2000)
r_2019 <- yearly_rasters[[20]]  # Last raster (2019)

# Compute the overall time average
time_avg_raster <- mean(yearly_rasters)

# Convert each raster to a dataframe
df_2000 <- as.data.frame(r_2000, xy = TRUE)
df_2019 <- as.data.frame(r_2019, xy = TRUE)
df_avg <- as.data.frame(time_avg_raster, xy = TRUE)

# Merge dataframes
df <- merge(df_2000, df_2019, by = c("x", "y"), suffixes = c("_2000", "_2019"))
df <- merge(df, df_avg, by = c("x", "y"))
colnames(df) <- c("x", "y", "temp_2000", "temp_2019", "avg_temp")
df$x <- round(df$x, 1)
df$y <- round(df$y, 1)

write.csv(df, "temperature_summary.csv", row.names = FALSE)
```


```{r}
library(ggplot2)

ggplot() + 
  geom_raster(data = df, mapping = aes(x = x, y = y, fill = avg_temp)) +
  coord_fixed() +
  scale_fill_viridis_c(name = "°C") +
  ggtitle("All-time Avg Temp 2000-2019")
```

```{r}
library(patchwork)

# Compute common limits
temp_min <- min(df$temp_2000, df$temp_2019, na.rm = TRUE)
temp_max <- max(df$temp_2000, df$temp_2019, na.rm = TRUE)

p1 <- ggplot() + 
  geom_raster(data = df, mapping = aes(x = x, y = y, fill = temp_2000)) +
  coord_fixed() +
  scale_fill_viridis_c(name = "°C", limits = c(temp_min, temp_max)) +
  ggtitle("Avg Temp 2000")

p2 <- ggplot() + 
  geom_raster(data = df, mapping = aes(x = x, y = y, fill = temp_2019)) +
  coord_fixed() +
  scale_fill_viridis_c(name = "°C", limits = c(temp_min, temp_max)) +
  ggtitle("Avg Temp 2019")

p1 + p2 + plot_layout(ncol = 1)
```

```{r}
ggplot() +
  geom_histogram(data = df, aes(x = temp_2000), 
                 fill = "steelblue", alpha = 0.5, bins = 100) +
  geom_histogram(data = df, aes(x = temp_2019), 
                 fill = "tomato", alpha = 0.5, bins = 100) +
  labs(x = "Temperature (°C)", y = "Count", title = "Histogram of Temperatures: 2000 vs 2019") +
  scale_x_continuous(limits = c(-35, 35), breaks = seq(-35, 35, 5)) +
  guides(fill = guide_legend(title = "Year"))
```

